# Сколько секунд нельзя писать команды и выходить из игры после вступления в пвп режим (в секундах)

interval: 20

# Команды которое нельзя писать после вступление в пвп режим

blocked-commands:
    - /spawn
    - /home
    - /tpa
    - /call
    - /hm
    - /sp
    - /tp
    - /kill
    - /gm 
    - /gamemode 
    - /fly
    - /god
    - /gma
    - /gmc